# Development shell configuration
{
  pkgs,
  lib,
  rustSrc,
  rustAnalyzer,
  toolChainNightly,
  devPackages,
}: let
  # Wrapper to run cargo with nightly toolchain (for udeps, miri, sanitizers, etc.)
  # Prepends full nightly toolchain to PATH so rustc, cargo, etc. are all nightly
  cargo-nightly = pkgs.writeShellScriptBin "cargo-nightly" ''
    export PATH="${toolChainNightly}/bin:$PATH"
    exec cargo "$@"
  '';
in
  pkgs.mkShell {
    name = "eidetica";
    shellHook = ''
      echo "Eidetica Development Shell"
      echo ""
      echo "Run 'just' to see available commands"
      echo ""

      # Buck2's C build-script shims use execve, so their tools need absolute paths.
      # Generate a standard local Buck config rather than shadowing the upstream CLI.
      if [ -f .buckconfig ] && command -v buck2 >/dev/null 2>&1; then
        mkdir -p .buckconfig.d
        buck_config=$(mktemp .buckconfig.d/nix-dev-shell.XXXXXX)
        {
          echo "# Generated by the Eidetica Nix dev shell"
          echo '[cxx]'
          printf 'compiler = %s\n' "$(command -v clang)"
          printf 'cxx_compiler = %s\n' "$(command -v clang++)"
          printf 'linker = %s\n' "$(command -v clang++)"
          printf 'archiver = %s\n' "$(command -v ar)"
        } > "$buck_config"
        if cmp -s "$buck_config" .buckconfig.d/nix-dev-shell; then
          rm "$buck_config"
        else
          mv "$buck_config" .buckconfig.d/nix-dev-shell
        fi
      fi
    '';

    # Inherit build environments from all dev packages
    # This ensures all build dependencies are available
    inputsFrom = builtins.attrValues devPackages;

    # Additional development tools
    packages =
      [
        # Nightly toolchain wrapper (for udeps, miri, sanitizers, etc.)
        cargo-nightly
      ]
      ++ lib.optionals (pkgs.stdenv.hostPlatform.system == "x86_64-linux") (with pkgs; [
        # Buck2 developer build currently supports Linux x86_64 only.
        buck2
        reindeer
        clang
        lld
        binutils
      ])
      ++ [
        # LSP — not part of the build toolchain, so the devshell adds it directly
        rustAnalyzer
      ]
      ++ (with pkgs; [
        # CI/CD tools
        act # Run GitHub Actions locally
        just # Task runner
        nix-fast-build # Fast parallel Nix builds

        # Linting tools
        deadnix # Find dead Nix code
        statix # Lint Nix code
        shellcheck # Lint shell scripts
        yamllint # Lint YAML files
        actionlint # Lint GitHub Actions workflows
        zizmor # Audit GitHub Actions security
        hadolint # Lint Dockerfiles
        markdownlint-cli # Lint Markdown files
        gitleaks # Detect secrets in code

        # Code formatting and quality
        alejandra # Nix formatter
        prettier # General formatter
        typos # Spell checker

        # Release management
        release-plz # Automated releases

        # Performance analysis
        cargo-flamegraph # Profiling

        # Code coverage
        lcov # Merge coverage reports

        # Documentation
        mdbook # Book generation
        mdbook-mermaid # Mermaid diagrams
        lychee # Link validation

        # Memory safety analysis
        cargo-careful # Run with extra runtime checks
      ]);

    # Environment variables

    # Rust standard library sources for tools like rust-analyzer
    RUST_SRC_PATH = "${rustSrc}/lib/rustlib/src/rust/library";

    # Enable debug symbols in release builds for better profiling
    CARGO_PROFILE_RELEASE_DEBUG = true;

    # Default logging level for development
    RUST_LOG = "eidetica=debug";
  }
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    RUSTFLAGS = "-C link-arg=-fuse-ld=mold";
  }
