# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task --list
    silent: true
  dev:
    desc: Quick development feedback (build + test + clippy)
    aliases: [d]
    cmds:
      - task: build
      - task: test
      - task: clippy
  fix:
    desc: Run automatic fixes
    cmds:
      - task: clippy:fix
      - task: fmt
  ci:full:
    desc: Run CI locally in containers
    cmds:
      - act --workflows .github/workflows/rust.yml
  ci:local:
    desc: Run CI locally
    aliases: [ci]
    deps: [fix]
    cmds:
      - task: audit
      - task: doc
      - task: clippy
      - task: build
      - task: test:full
  ci:nix:
    desc: Run Nix CI checks
    deps: [nix:build, nix:check]
  nix:check:
    desc: Run Nix CI checks
    cmds:
      - nix-fast-build --no-link
  nix:build:
    desc: Run Nix Build
    cmds:
      - nix build
  nix:integration:
    desc: Run NixOS VM integration tests (Linux only, slow)
    cmds:
      - nix build .#integration-nixos --no-link
      - nix build .#integration-container --no-link
  nix:full:
    desc: Run all Nix checks including VM integration tests
    cmds:
      - task: nix:check
      - task: nix:integration
  clippy:
    desc: Run clippy
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings
  clippy:fix:
    desc: Run clippy fixes
    cmds:
      - cargo clippy --workspace --fix --allow-dirty --all-targets --all-features --allow-no-vcs -- -D warnings
  fmt:
    desc: Run all formatters
    cmds:
      - cargo fmt --all
      - alejandra . --quiet
      - prettier --write . --log-level warn
  test:
    desc: Run tests
    aliases: [t]
    cmds:
      - cargo nextest run --workspace --all-features --no-fail-fast --status-level fail
  test:doc:
    desc: Run doc tests
    cmds:
      - cargo test --doc --workspace --all-features --quiet
  test:full:
    desc: Run all tests
    aliases: [tf]
    cmds:
      - task: test
      - task: test:doc
      - task: test:book
  test:ignored:
    desc: Run tests including ignored ones
    aliases: [ti]
    cmds:
      - cargo nextest run --workspace --all-features --no-fail-fast --status-level fail --run-ignored all
  test:minimal:
    desc: Test library with no default features
    cmds:
      - cargo build -p eidetica --no-default-features
      - cargo test -p eidetica --no-default-features --features testing
  doc:
    desc: Build the documentation
    cmd: cargo doc --workspace --all-features --no-deps --quiet
  doc:full:
    desc: Build the documentation with all dependencies
    cmd: cargo doc --workspace --all-features --quiet
  audit:
    desc: Run security and license checks (advisories, licenses, bans, sources)
    # Note: We use cargo-deny instead of cargo-audit because cargo-deny properly
    # resolves features and ignores unused optional dependencies in Cargo.lock
    cmds:
      - cargo deny check
  udeps:
    desc: Check for unused dependencies
    cmd: cargo udeps --workspace --all-targets
  build:debug:
    desc: Build the project
    aliases: [b, build]
    cmd: cargo build --workspace --all-targets --all-features --quiet
  build:release:
    desc: Build the project release
    aliases: [br, release]
    cmd: cargo build --workspace --all-targets --all-features --release --quiet
  clean:
    desc: Clean all build artifacts and caches
    cmd: cargo clean
  coverage:
    desc: Generate coverage data (inmemory backend)
    aliases: [cov]
    cmd: cargo tarpaulin --workspace --skip-clean --all-features --output-dir coverage --out lcov --engine llvm
  coverage:sqlite:
    desc: Generate coverage data (sqlite backend)
    aliases: [cov:sqlite]
    env:
      TEST_BACKEND: sqlite
    cmd: cargo tarpaulin --workspace --skip-clean --all-features --output-dir coverage --out lcov --engine llvm
  coverage:postgres:
    desc: Generate coverage data (postgres backend)
    aliases: [cov:postgres]
    vars:
      CONTAINER_NAME: eidetica-coverage-postgres
      DB_NAME: eidetica_test
      DB_PORT: 54322
    cmds:
      - docker rm -f {{.CONTAINER_NAME}} 2>/dev/null || true
      - defer: docker rm -f {{.CONTAINER_NAME}} 2>/dev/null || true
      - |
        echo "Starting PostgreSQL container..."
        docker run -d --name {{.CONTAINER_NAME}} \
          -e POSTGRES_DB={{.DB_NAME}} \
          -e POSTGRES_HOST_AUTH_METHOD=trust \
          -p {{.DB_PORT}}:5432 \
          postgres:16-alpine
      - |
        echo "Waiting for PostgreSQL to be ready..."
        for i in $(seq 1 30); do
          if docker exec {{.CONTAINER_NAME}} pg_isready -U postgres -d {{.DB_NAME}} >/dev/null 2>&1; then
            echo "PostgreSQL is ready!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Timed out waiting for PostgreSQL"
            exit 1
          fi
          sleep 1
        done
      - |
        echo "Running coverage against PostgreSQL..."
        TEST_BACKEND=postgres \
        TEST_POSTGRES_URL="postgres://postgres@localhost:{{.DB_PORT}}/{{.DB_NAME}}" \
        cargo tarpaulin --workspace --skip-clean --all-features --output-dir coverage --out lcov --engine llvm
  coverage:all:
    desc: Generate coverage for all backends and merge reports
    aliases: [cov:all]
    cmds:
      - task: coverage
      - mv coverage/lcov.info coverage/lcov-inmemory.info
      - task: coverage:sqlite
      - mv coverage/lcov.info coverage/lcov-sqlite.info
      - task: coverage:postgres
      - mv coverage/lcov.info coverage/lcov-postgres.info
      - |
        echo "Merging coverage reports..."
        lcov -a coverage/lcov-inmemory.info -a coverage/lcov-sqlite.info -a coverage/lcov-postgres.info -o coverage/lcov.info
        echo "Merged coverage report: coverage/lcov.info"
  coverage:ignored:
    desc: Generate coverage data including ignored tests
    aliases: [cov:i]
    cmd: cargo tarpaulin --workspace --skip-clean --all-features --output-dir coverage --out lcov --engine llvm --ignored --no-fail-fast
  test:todo:
    desc: Run the todo example integration test
    dir: examples/todo
    cmd: ./test.sh
  book:
    desc: Build the mdbook documentation (includes rustdoc and link checking)
    cmds:
      - cargo doc -p eidetica --all-features --no-deps --quiet
      - ln -sfn ../../target/doc docs/src/rustdoc
      - mdbook build docs
  book:serve:
    desc: Serve the mdbook documentation locally
    cmds:
      - task: book
      - mdbook serve docs --open
  book:test:
    desc: Test code examples and check links in the mdbook
    aliases: [test:book]
    deps: [book:links]
    cmds:
      # The book tests require a single copy of libeidetica target/debug/deps
      # This is a workaround to remove and rebuild only 1
      - rm -f target/debug/deps/libeidetica-*.rlib target/debug/deps/libeidetica-*.rmeta
      - cargo build -p eidetica
      - RUST_LOG=error mdbook test docs -L target/debug/deps
  book:clean:
    desc: Clean the mdbook build directory
    cmds:
      - mdbook clean docs
      - rm -rf docs/src/rustdoc
  book:links:
    desc: Check internal links in documentation
    deps: [book]
    cmds:
      - lychee --offline --exclude-path 'rustdoc' docs/book
  book:links:all:
    desc: Check all links including external URLs (slow, run locally)
    deps: [book]
    cmds:
      - lychee --exclude-path 'rustdoc' --exclude-path 'fonts' docs/book
  book:stats:
    desc: Show code block test coverage statistics
    cmd: |
      tested=$(grep -r '```rust$' docs/src | wc -l)
      total=$(grep -r '```rust' docs/src | wc -l)
      echo "${tested}/${total} Code Blocks tested"
  bench:
    desc: Run benchmarks and open HTML report
    aliases: [benchmark]
    cmds:
      - cargo bench --workspace
      - xdg-open target/criterion/report/index.html 2>/dev/null
  min-versions:
    desc: Check the minimum versions of the dependencies
    cmds:
      - cargo update -Z minimal-versions && cargo build --workspace --all-targets --all-features --quiet && cargo nextest run --workspace --all-features --status-level fail
      # We do _not_ want to run the clippy check here, because it will fail
  container:docker:
    desc: Build Docker container image
    cmds:
      - docker build -t eidetica:dev .
  container:nix:
    desc: Build and load Nix OCI container image
    cmds:
      - nix build .#eidetica-image
      - docker load < ./result

  test:postgres:
    desc: Run tests against PostgreSQL (requires docker)
    aliases: [tp]
    vars:
      CONTAINER_NAME: eidetica-test-postgres
      DB_NAME: eidetica_test
      DB_PORT: 54321
    cmds:
      - docker rm -f {{.CONTAINER_NAME}} 2>/dev/null || true
      - defer: docker rm -f {{.CONTAINER_NAME}} 2>/dev/null || true
      - |
        echo "Starting PostgreSQL container..."
        docker run -d --name {{.CONTAINER_NAME}} \
          -e POSTGRES_DB={{.DB_NAME}} \
          -e POSTGRES_HOST_AUTH_METHOD=trust \
          -p {{.DB_PORT}}:5432 \
          postgres:16-alpine
      - |
        echo "Waiting for PostgreSQL to be ready..."
        for i in $(seq 1 30); do
          if docker exec {{.CONTAINER_NAME}} pg_isready -U postgres -d {{.DB_NAME}} >/dev/null 2>&1; then
            echo "PostgreSQL is ready!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Timed out waiting for PostgreSQL"
            exit 1
          fi
          sleep 1
        done
      - |
        echo "Running tests against PostgreSQL..."
        TEST_BACKEND=postgres \
        TEST_POSTGRES_URL="postgres://postgres@localhost:{{.DB_PORT}}/{{.DB_NAME}}" \
        cargo nextest run --workspace --features postgres --no-fail-fast --status-level fail

  test:sqlite:
    desc: Run tests against SQLite backend
    aliases: [ts]
    cmds:
      - TEST_BACKEND=sqlite cargo nextest run --workspace --features sqlite --no-fail-fast --status-level fail

  test:backends:
    desc: Run tests against all backends
    aliases: [tb]
    cmds:
      - echo "=== Testing InMemory backend ==="
      - task: test
      - echo "=== Testing SQLite backend ==="
      - task: test:sqlite
      - echo "=== Testing PostgreSQL backend ==="
      - task: test:postgres
