# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task --list
    silent: true
  ci:full:
    desc: Run CI locally in containers
    cmd: act
  ci:local:
    desc: Run CI locally
    aliases: [ci]
    deps:
      [audit, doc, fmt, test, nix:check, nix:build, clippy, build]
  nix:check:
    desc: Run Nix CI checks
    cmds:
      - nix flake check
  nix:build:
    desc: Run Nix Build
    cmds:
      - nix build
  clippy:
    desc: Run clippy
    cmd: cargo clippy
  fmt:
    desc: Run all formatters
    cmds:
      - cargo fmt --all
      - alejandra .
  up:
    desc: Start the testing database
    aliases: [db:up, db:start]
    cmd: source ./tests/test.sh up
  down:
    desc: Stop the testing database
    aliases: [db:down, db:stop]
    cmd: source ./tests/test.sh down
  test:
    desc: Run all tests
    deps: [db:start]
    aliases: [t]
    cmd: cargo nextest run
  doc:
    desc: Build the documentation
    cmd: cargo doc
  audit:
    desc: Run cargo security audit
    cmd: cargo audit
  build:
    desc: Build the project
    aliases: [b]
    cmd: cargo build
