# Forgejo CI workflow for Nix builds
#
# Optional Repository Secrets (configure in Forgejo Settings → Secrets → Actions):
#   NIX_EXTRA_SUBSTITUTERS: Space-separated list of additional binary caches
#   NIX_EXTRA_TRUSTED_PUBLIC_KEYS: Space-separated public keys for extra substituters
#   ATTIC_SERVER_URL: Attic server URL for login (required if using ATTIC_AUTH_TOKEN)
#   ATTIC_AUTH_TOKEN: Token for pushing to Attic (eidetica cache)
#   CACHIX_AUTH_TOKEN: Token for pushing to Cachix (eidetica cache)
#
name: Nix

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest@sha256:081b65e50a5c4e6ef4a9094a462da3b83ff76bfec70236eb010047fcee36e11c
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs="

          if [ -n "$NIX_EXTRA_SUBSTITUTERS" ]; then
            SUBSTITUTERS="$NIX_EXTRA_SUBSTITUTERS $SUBSTITUTERS"
          fi

          if [ -n "$NIX_EXTRA_TRUSTED_PUBLIC_KEYS" ]; then
            TRUSTED_KEYS="$TRUSTED_KEYS $NIX_EXTRA_TRUSTED_PUBLIC_KEYS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          NIX_EXTRA_SUBSTITUTERS: "${{ secrets.NIX_EXTRA_SUBSTITUTERS }}"
          NIX_EXTRA_TRUSTED_PUBLIC_KEYS: "${{ secrets.NIX_EXTRA_TRUSTED_PUBLIC_KEYS }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build lint checks
        run: |
          nix build .#lint --no-link
          nix build .#checks.x86_64-linux.treefmt --no-link
          nix build .#checks.x86_64-linux.eval-nixos --no-link
          nix build .#checks.x86_64-linux.eval-hm --no-link

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest@sha256:081b65e50a5c4e6ef4a9094a462da3b83ff76bfec70236eb010047fcee36e11c
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs="

          if [ -n "$NIX_EXTRA_SUBSTITUTERS" ]; then
            SUBSTITUTERS="$NIX_EXTRA_SUBSTITUTERS $SUBSTITUTERS"
          fi

          if [ -n "$NIX_EXTRA_TRUSTED_PUBLIC_KEYS" ]; then
            TRUSTED_KEYS="$TRUSTED_KEYS $NIX_EXTRA_TRUSTED_PUBLIC_KEYS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          NIX_EXTRA_SUBSTITUTERS: "${{ secrets.NIX_EXTRA_SUBSTITUTERS }}"
          NIX_EXTRA_TRUSTED_PUBLIC_KEYS: "${{ secrets.NIX_EXTRA_TRUSTED_PUBLIC_KEYS }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test checks
        run: nix build .#test --no-link

  doc:
    name: Doc
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest@sha256:081b65e50a5c4e6ef4a9094a462da3b83ff76bfec70236eb010047fcee36e11c
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs="

          if [ -n "$NIX_EXTRA_SUBSTITUTERS" ]; then
            SUBSTITUTERS="$NIX_EXTRA_SUBSTITUTERS $SUBSTITUTERS"
          fi

          if [ -n "$NIX_EXTRA_TRUSTED_PUBLIC_KEYS" ]; then
            TRUSTED_KEYS="$TRUSTED_KEYS $NIX_EXTRA_TRUSTED_PUBLIC_KEYS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          NIX_EXTRA_SUBSTITUTERS: "${{ secrets.NIX_EXTRA_SUBSTITUTERS }}"
          NIX_EXTRA_TRUSTED_PUBLIC_KEYS: "${{ secrets.NIX_EXTRA_TRUSTED_PUBLIC_KEYS }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build doc checks
        run: nix build .#doc --no-link

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest@sha256:081b65e50a5c4e6ef4a9094a462da3b83ff76bfec70236eb010047fcee36e11c
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs="

          if [ -n "$NIX_EXTRA_SUBSTITUTERS" ]; then
            SUBSTITUTERS="$NIX_EXTRA_SUBSTITUTERS $SUBSTITUTERS"
          fi

          if [ -n "$NIX_EXTRA_TRUSTED_PUBLIC_KEYS" ]; then
            TRUSTED_KEYS="$TRUSTED_KEYS $NIX_EXTRA_TRUSTED_PUBLIC_KEYS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          NIX_EXTRA_SUBSTITUTERS: "${{ secrets.NIX_EXTRA_SUBSTITUTERS }}"
          NIX_EXTRA_TRUSTED_PUBLIC_KEYS: "${{ secrets.NIX_EXTRA_TRUSTED_PUBLIC_KEYS }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        run: |
          nix build .#eidetica --no-link
          nix build .#eidetica-lib --no-link

  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [lint, test, doc, build]
    container:
      image: nixos/nix:latest@sha256:081b65e50a5c4e6ef4a9094a462da3b83ff76bfec70236eb010047fcee36e11c
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs="

          if [ -n "$NIX_EXTRA_SUBSTITUTERS" ]; then
            SUBSTITUTERS="$NIX_EXTRA_SUBSTITUTERS $SUBSTITUTERS"
          fi

          if [ -n "$NIX_EXTRA_TRUSTED_PUBLIC_KEYS" ]; then
            TRUSTED_KEYS="$TRUSTED_KEYS $NIX_EXTRA_TRUSTED_PUBLIC_KEYS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          NIX_EXTRA_SUBSTITUTERS: "${{ secrets.NIX_EXTRA_SUBSTITUTERS }}"
          NIX_EXTRA_TRUSTED_PUBLIC_KEYS: "${{ secrets.NIX_EXTRA_TRUSTED_PUBLIC_KEYS }}"

      - name: Configure Attic
        if: "${{ secrets.ATTIC_AUTH_TOKEN != '' && secrets.ATTIC_SERVER_URL != '' }}"
        run: |
          nix profile add nixpkgs#attic-client
          attic login eidetica "$ATTIC_SERVER_URL" "$ATTIC_AUTH_TOKEN"
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"
          ATTIC_AUTH_TOKEN: "${{ secrets.ATTIC_AUTH_TOKEN }}"

      - name: Install Cachix
        if: "${{ secrets.CACHIX_AUTH_TOKEN != '' }}"
        run: |
          nix profile add nixpkgs#cachix
          cachix authtoken "$CACHIX_AUTH_TOKEN"
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push artifacts
        run: |
          for pkg in eidetica eidetica-lib eidetica-image; do
            echo "Building $pkg..."
            PATHS=$(nix build .#$pkg --no-link --print-out-paths)

            if command -v attic &> /dev/null; then
              echo "Pushing to Attic..."
              echo "$PATHS" | xargs attic push eidetica
            fi

            if [ -n "$CACHIX_AUTH_TOKEN" ]; then
              echo "Pushing to Cachix..."
              echo "$PATHS" | cachix push eidetica
            fi
          done
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
