# Forgejo CI workflow for Nix builds
#
# Repository Secrets (configure in Forgejo Settings → Secrets → Actions):
#   ATTIC_SERVER_URL: Attic server URL (required for caching)
#   ATTIC_AUTH_TOKEN: Token for Attic cache
#   CACHIX_AUTH_TOKEN: Token for pushing to Cachix (eidetica cache)
#   CODECOV_TOKEN: Token for uploading coverage to Codecov
#
name: Nix

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest@sha256:d5cce2440bda1f966357732c06d86cb92368069fb52dfb6b2bae8725eea488a5
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs= eidetica:hm/EK+V7LITUUdJi9AxDNic5j6cB1EhSQy0R+z2uoPU="

          # Add Attic as high-priority substituter if available
          if [ -n "$ATTIC_SERVER_URL" ]; then
            SUBSTITUTERS="$ATTIC_SERVER_URL/eidetica?priority=10 $SUBSTITUTERS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          build-dir = /tmp
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"

      - name: Configure Attic
        if: "${{ secrets.ATTIC_AUTH_TOKEN != '' && secrets.ATTIC_SERVER_URL != '' }}"
        run: |
          nix profile add nixpkgs#attic-client
          attic login eidetica "$ATTIC_SERVER_URL" "$ATTIC_AUTH_TOKEN"
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"
          ATTIC_AUTH_TOKEN: "${{ secrets.ATTIC_AUTH_TOKEN }}"

      - name: Install tools
        run: nix profile add nixpkgs#just nixpkgs#nix-fast-build nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run Nix checks
        run: just nix check

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: nixos/nix:latest@sha256:d5cce2440bda1f966357732c06d86cb92368069fb52dfb6b2bae8725eea488a5
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs= eidetica:hm/EK+V7LITUUdJi9AxDNic5j6cB1EhSQy0R+z2uoPU="

          if [ -n "$ATTIC_SERVER_URL" ]; then
            SUBSTITUTERS="$ATTIC_SERVER_URL/eidetica?priority=10 $SUBSTITUTERS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          build-dir = /tmp
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"

      - name: Configure Attic
        if: "${{ secrets.ATTIC_AUTH_TOKEN != '' && secrets.ATTIC_SERVER_URL != '' }}"
        run: |
          nix profile add nixpkgs#attic-client
          attic login eidetica "$ATTIC_SERVER_URL" "$ATTIC_AUTH_TOKEN"
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"
          ATTIC_AUTH_TOKEN: "${{ secrets.ATTIC_AUTH_TOKEN }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run coverage (sqlite)
        run: |
          nix build .#coverage.sqlite -o coverage-sqlite
          cp coverage-sqlite/lcov.info lcov-sqlite.info
          if command -v attic &> /dev/null; then
            attic push eidetica coverage-sqlite
          fi

      - name: Run coverage (inmemory)
        run: |
          nix build .#coverage.inmemory -o coverage-inmemory
          cp coverage-inmemory/lcov.info lcov-inmemory.info
          if command -v attic &> /dev/null; then
            attic push eidetica coverage-inmemory
          fi

      - name: Upload coverage to Codecov
        uses: https://github.com/codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: arcuru/eidetica
          files: lcov-sqlite.info,lcov-inmemory.info
          fail_ci_if_error: false

  sanitize:
    name: Sanitizers
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: nixos/nix:latest@sha256:d5cce2440bda1f966357732c06d86cb92368069fb52dfb6b2bae8725eea488a5
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs= eidetica:hm/EK+V7LITUUdJi9AxDNic5j6cB1EhSQy0R+z2uoPU="

          if [ -n "$ATTIC_SERVER_URL" ]; then
            SUBSTITUTERS="$ATTIC_SERVER_URL/eidetica?priority=10 $SUBSTITUTERS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          build-dir = /tmp
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"

      - name: Configure Attic
        if: "${{ secrets.ATTIC_AUTH_TOKEN != '' && secrets.ATTIC_SERVER_URL != '' }}"
        run: |
          nix profile add nixpkgs#attic-client
          attic login eidetica "$ATTIC_SERVER_URL" "$ATTIC_AUTH_TOKEN"
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"
          ATTIC_AUTH_TOKEN: "${{ secrets.ATTIC_AUTH_TOKEN }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run sanitizers
        run: |
          PATHS=$(nix build .#sanitize --no-link --print-out-paths)
          if command -v attic &> /dev/null; then
            echo "$PATHS" | xargs attic push eidetica
          fi

  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [check]
    container:
      image: nixos/nix:latest@sha256:d5cce2440bda1f966357732c06d86cb92368069fb52dfb6b2bae8725eea488a5
    steps:
      - name: Configure Nix with caches
        run: |
          mkdir -p ~/.config/nix

          SUBSTITUTERS="https://cache.nixos.org?priority=40 https://eidetica.cachix.org?priority=50"
          TRUSTED_KEYS="cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= eidetica.cachix.org-1:EDr+F/9jkD8aeThjJ4W3+4Yj3MH9fPx6slVLxF1HNSs= eidetica:hm/EK+V7LITUUdJi9AxDNic5j6cB1EhSQy0R+z2uoPU="

          if [ -n "$ATTIC_SERVER_URL" ]; then
            SUBSTITUTERS="$ATTIC_SERVER_URL/eidetica?priority=10 $SUBSTITUTERS"
          fi

          cat > ~/.config/nix/nix.conf <<EOF
          experimental-features = nix-command flakes
          build-dir = /tmp
          substituters = $SUBSTITUTERS
          trusted-public-keys = $TRUSTED_KEYS
          EOF
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"

      - name: Configure Attic
        if: "${{ secrets.ATTIC_AUTH_TOKEN != '' && secrets.ATTIC_SERVER_URL != '' }}"
        run: |
          nix profile add nixpkgs#attic-client
          attic login eidetica "$ATTIC_SERVER_URL" "$ATTIC_AUTH_TOKEN"
        env:
          ATTIC_SERVER_URL: "${{ secrets.ATTIC_SERVER_URL }}"
          ATTIC_AUTH_TOKEN: "${{ secrets.ATTIC_AUTH_TOKEN }}"

      - name: Install Cachix
        if: "${{ secrets.CACHIX_AUTH_TOKEN != '' }}"
        run: |
          nix profile add nixpkgs#cachix
          cachix authtoken "$CACHIX_AUTH_TOKEN"
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install Actions Deps
        run: nix profile add nixpkgs#nodejs

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Build and push artifacts
        run: |
          for pkg in eidetica eidetica-lib eidetica-image; do
            echo "Building $pkg..."
            PATHS=$(nix build .#$pkg --no-link --print-out-paths)

            if command -v attic &> /dev/null; then
              echo "Pushing to Attic..."
              echo "$PATHS" | xargs attic push eidetica
            fi

            if [ -n "$CACHIX_AUTH_TOKEN" ]; then
              echo "Pushing to Cachix..."
              echo "$PATHS" | cachix push eidetica
            fi
          done
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
