# Forgejo CI workflow for Rust checks, build, and tests
# Note: Uses full GitHub URLs for actions not in Forgejo's registry
name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.92.0"

jobs:
  check:
    name: Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-
            ${{ runner.os }}-rust-

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Build
        run: cargo build --workspace --all-targets --all-features

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine@sha256:23e88eb049fd5d54894d70100df61d38a49ed97909263f79d4ff4c30a5d5fca2
        env:
          POSTGRES_DB: eidetica_test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-
            ${{ runner.os }}-rust-

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install mdbook and nextest
        uses: https://github.com/taiki-e/install-action@0e76c5c569f13f7eb21e8e5b26fe710062b57b62 # v2
        with:
          tool: cargo-nextest@0.9.115,mdbook@0.4

      - name: Test (inmemory backend)
        run: cargo nextest run --workspace --all-features

      - name: Test (sqlite backend)
        run: cargo nextest run --workspace --all-features
        env:
          TEST_BACKEND: sqlite

      - name: Test (postgres backend)
        run: cargo nextest run --workspace --all-features
        env:
          TEST_BACKEND: postgres
          TEST_POSTGRES_URL: postgres://postgres@postgres:5432/eidetica_test

      - name: Test Doc Examples
        run: cargo test --doc --workspace --all-features

      - name: Test Documentation Examples
        run: |
          # The book tests require a single copy of libeidetica target/debug/deps
          # This is a workaround to remove and rebuild only 1
          rm -f target/debug/deps/libeidetica-*.rlib target/debug/deps/libeidetica-*.rmeta
          cargo build -p eidetica
          mdbook test docs -L target/debug/deps

      - name: Build with minimal features
        run: cargo build -p eidetica --no-default-features

      - name: Test with minimal features
        run: cargo nextest run -p eidetica --no-default-features --features testing
