# Forgejo CI workflow for Rust checks, build, and tests
# Note: Uses full GitHub URLs for actions not in Forgejo's registry
name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.92.0"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # Cache before Install Rust so cached toolchain is available
      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-
            ${{ runner.os }}-rust-

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-
            ${{ runner.os }}-rust-

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Build
        run: cargo build --workspace --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-
            ${{ runner.os }}-rust-

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install mdbook
        run: |
          if ! command -v mdbook &> /dev/null
          then
              cargo install mdbook --locked --version ^0.4
          fi

      - name: Test
        run: cargo test --workspace --all-features

      - name: Test Doc Examples
        run: cargo test --doc --workspace --all-features

      - name: Test Documentation Examples
        run: |
          # The book tests require a single copy of libeidetica target/debug/deps
          # This is a workaround to remove and rebuild only 1
          rm -f target/debug/deps/libeidetica-*.rlib target/debug/deps/libeidetica-*.rmeta
          cargo build -p eidetica
          mdbook test docs -L target/debug/deps

  test-minimal:
    name: Test Minimal Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-minimal-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-minimal-
            ${{ runner.os }}-rust-${{ env.RUST_VERSION }}-

      - name: Install Rust
        uses: https://github.com/dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Build with no default features
        run: cargo build -p eidetica --no-default-features

      - name: Test with no default features
        run: cargo test -p eidetica --no-default-features
