# Commits changed files, pushes the branch, and creates or updates a PR with
# hold labels. Designed for use after setup-deps-branch and an update step.
#
name: Commit and PR
description: Commit changes, push, and create/update a dependency PR with hold period

inputs:
  branch:
    description: "Branch name (e.g. deps/cargo-update)"
    required: true
  files:
    description: "Space-separated paths to diff/stage"
    required: true
  commit-message:
    description: "Conventional commit message"
    required: true
  pr-title:
    description: "PR title"
    required: true
  pr-body:
    description: "PR body content (hold section appended automatically)"
    required: true
  hold-days:
    description: "Days to hold before merge"
    required: false
    default: "7"
  update-comment:
    description: "Comment posted on existing PR updates"
    required: false
    default: "Updated with latest dependency changes."
  github-token:
    description: "Token with contents:write + pull-requests:write"
    required: true

outputs:
  changed:
    description: "Whether any files changed (true/false)"
    value: ${{ steps.check.outputs.changed }}
  pr-number:
    description: "PR number (empty if no changes)"
    value: ${{ steps.pr.outputs.number }}

runs:
  using: composite
  steps:
    - name: Check for changes
      id: check
      shell: bash
      run: |
        if git diff --quiet -- ${{ inputs.files }}; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
          echo "No changes detected."
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push
      if: steps.check.outputs.changed == 'true'
      shell: bash
      run: |
        git add -- ${{ inputs.files }}
        git commit -m "${{ inputs.commit-message }}"
        git push --force-with-lease origin "${{ inputs.branch }}"

    - name: Calculate hold date
      if: steps.check.outputs.changed == 'true'
      id: hold
      shell: bash
      run: |
        HOLD_DAYS="${{ inputs.hold-days }}"
        HOLD_DATE=$(date -u -d "+${HOLD_DAYS} days" +%Y-%m-%d)
        echo "date=$HOLD_DATE" >> "$GITHUB_OUTPUT"
        echo "days=$HOLD_DAYS" >> "$GITHUB_OUTPUT"

    - name: Create or update PR
      if: steps.check.outputs.changed == 'true'
      id: pr
      shell: bash
      run: |
        HOLD_SECTION=$(cat <<HOLD_EOF

        ### Hold

        This PR is on hold until **$HOLD_DATE** ($HOLD_DAYS-day waiting period).
        The \`on-hold\` label will be automatically removed after the hold expires.

        <!-- hold-until: $HOLD_DATE -->
        HOLD_EOF
        )

        FULL_BODY="${PR_BODY}${HOLD_SECTION}"

        EXISTING_PR=$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number // empty')

        if [ -n "$EXISTING_PR" ]; then
          gh pr edit "$EXISTING_PR" --body "$FULL_BODY"
          gh pr edit "$EXISTING_PR" --add-label dependencies --add-label on-hold
          gh pr comment "$EXISTING_PR" --body "$UPDATE_COMMENT"
          echo "number=$EXISTING_PR" >> "$GITHUB_OUTPUT"
        else
          PR_URL=$(gh pr create \
            --head "$BRANCH" \
            --base main \
            --title "$PR_TITLE" \
            --body "$FULL_BODY" \
            --label dependencies \
            --label on-hold)
          PR_NUM=$(echo "$PR_URL" | grep -o '[0-9]*$')
          echo "number=$PR_NUM" >> "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        BRANCH: ${{ inputs.branch }}
        PR_BODY: ${{ inputs.pr-body }}
        PR_TITLE: ${{ inputs.pr-title }}
        UPDATE_COMMENT: ${{ inputs.update-comment }}
        HOLD_DATE: ${{ steps.hold.outputs.date }}
        HOLD_DAYS: ${{ steps.hold.outputs.days }}
