name: Codeberg

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  mirror:
    uses: arcuru/actions/.github/workflows/codeberg-mirror.yml@c8144123ad5a2c6316b7becab8233b68dfa637d9 # v0.2.1
    with:
      runs-on: ubicloud-standard-2
      environment: mirror
      destination: git@codeberg.org:arcuru/eidetica.git
    secrets:
      ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
