name: Codeberg

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  mirror:
    uses: arcuru/actions/.github/workflows/codeberg-mirror.yml@31c804a9c15602300e5e292e80cac1ad5512a21a # main
    with:
      runs-on: ubicloud-standard-2
      environment: mirror
      destination: git@codeberg.org:arcuru/eidetica.git
    secrets:
      ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
